#ifndef TWBASE_INCLUDE_GUARD_TWBASECONFIG_HPP
#define TWBASE_INCLUDE_GUARD_TWBASECONFIG_HPP

#ifndef TWBASE_NAMESPACE
  #define TWBASE_NAMESPACE twbase
#endif

#endif // TWBASE_INCLUDE_GUARD_TWBASECONFIG_HPP